main: net.tfminecraft.geminfusion.InfusionMain
api-version: '1.21.10'
name: GemInfusion
version: ${project.version}
author: Drefvelin

depend: [TLibs, MMOItems, MythicLib]
softdepend: [MMOCore]

commands:
  geminfusion:
    usage: /<command> reload | select <projectId>
    description: Gem Infusion and goldsmithing admin command

permissions:
  geminfusion.admin:
    description: Access to GemInfusion admin commands
    default: op
  professions.goldsmith:
    description: Use goldsmithing tables, tools, and project menu
    default: false
